name: Automated Testing Demo

on:
  push:
    branches:
      - main  # Triggers the workflow on push to the 'main' branch
  pull_request:
    branches:
      - main  # Triggers the workflow on pull requests to the 'main' branch

jobs:
  test:
    runs-on: ubuntu-latest  # Specifies the type of runner to use
    
    steps:
    - name: Checkout repository
      uses: actions/checkout@v2  # Checks out the repository

    - name: Set up Node.js
      uses: actions/setup-node@v2
      with:
        node-version: '14'  # Specify the Node.js version

    - name: Install dependencies
      run: npm install  # Installs project dependencies

    - name: Run tests
      run: npm test  # Runs the test script defined in package.json
